server:
  port: 8082
  
spring:
  application:
    name: sgi-productos
  config:
    import: optional:configserver:http://localhost:8888/config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3&characterEncoding=UTF-8
    username: client
    password: Tu441n6
  jpa:
    hibernate:
      ddl-auto: none 
    database: mysql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    time-zone: America/Buenos_Aires
  

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
