server:
  port: 8080

spring:
  application:
    name: sgi-gateway
  
  eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
