server:
  port: 8090

spring:
  application:
    name: pwc-usuarios
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/renault2?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 